name: epic_benchmarks
channels:
  - conda-forge
dependencies:
  - python <= 3.8
  - pyyaml
  - pydantic
  - pydantic-yaml
  - pydantic-cli
  - pydantic-settings
  - lxml
  - jupyter 
  - numpy
  - pandas
  - uproot
  - matplotlib
  - seaborn
  - uncertainties
  - lmfit
  - parsl
  - setuptools
  - pip
  - pip:
    - .