name: epic_benchmarks
channels:
  - conda-forge
dependencies:
  - pyyaml
  - lxml
  - jupyter 
  - numpy
  - pandas
  - uproot
  - matplotlib
  - seaborn
  - uncertainties
  - lmfit
  - parsl
  - setuptools
  - pip
  - pip:
    - .
