name: ePIC_benchmarks
channels:
  - conda-forge
dependencies:
  - python <= 3.12
  - pyyaml
  - pydantic
  - mypy
  - lxml
  - jupyter 
  - numpy
  - pandas
  - uproot
  - matplotlib
  - seaborn
  - uncertainties
  - lmfit
  - parsl
  - setuptools
  - sphinx
  - sphinx-copybutton
  - pydata-sphinx-theme
  - graphviz
  - pip
  - pip:
    - -e .
    - pydantic-xml
    - pydantic-settings
    - parsl[monitoring, visualization]
    - pip-tools
    - autodoc_pydantic
    - sphinx-gitref
    - sphinx_rtd_theme
    - autodoc_pydantic[erdantic]
    - sphinx-book-theme
    - sphinxawesome-theme