[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.setuptools.dynamic]
dependencies = { file = ["docs/requirements.txt"] }

[project]
name = "ePIC_benchmarks"
authors = [{name = "Amir Abdou", email = "AmirKS@lbl.gov"}]
dynamic = ["version", "description"]