[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ePIC Benchmarks"
authors = [{name = "Amir Abdou", email = "AmirKS@lbl.gov"}]
dynamic = ["version", "description"]